# Generated by Django 5.1 on 2024-08-30 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_post_title_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='preview',
            field=models.TextField(blank=True, help_text='Optional preview text for the post.'),
        ),
    ]
