# Generated by Django 5.1 on 2024-09-17 16:37

from django.db import migrations
from django.utils.text import slugify

def generate_category_slugs(apps, schema_editor):
    Category = apps.get_model('core', 'Category')
    for category in Category.objects.all():
        base_slug = slugify(category.name)
        slug = base_slug
        n = 1
        while Category.objects.filter(slug=slug).exists():
            slug = f"{base_slug}-{n}"
            n += 1
        category.slug = slug
        category.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_post_body'),
    ]

    operations = [
    ]
