# Generated by Django 5.1 on 2024-09-17 16:48

from django.db import migrations
from django.utils.text import slugify

def generate_slugs(apps, schema_editor, model_name):
    Model = apps.get_model('core', model_name)
    for instance in Model.objects.all():
        base_slug = slugify(instance.name if hasattr(instance, 'name') else instance.title)
        slug = base_slug
        n = 1
        while Model.objects.filter(slug=slug).exists():
            slug = f"{base_slug}-{n}"
            n += 1
        instance.slug = slug
        instance.save()

def generate_post_slugs(apps, schema_editor):
    generate_slugs(apps, schema_editor, 'Post')

def generate_tag_slugs(apps, schema_editor):
    generate_slugs(apps, schema_editor, 'Tag')

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_generate_category_slugs'),
    ]

    operations = [
        migrations.RunPython(generate_post_slugs),
        migrations.RunPython(generate_tag_slugs),
    ]