# Generated by Django 5.1 on 2024-09-17 16:49

from django.db import migrations, models
from django.utils.text import slugify

def generate_slugs(apps, schema_editor):
    for model_name in ['Category', 'Post', 'Tag']:
        Model = apps.get_model('core', model_name)
        for instance in Model.objects.all():
            if not instance.slug:
                base_slug = slugify(instance.name if hasattr(instance, 'name') else instance.title)
                unique_slug = base_slug
                num = 1
                while Model.objects.filter(slug=unique_slug).exists():
                    unique_slug = f"{base_slug}-{num}"
                    num += 1
                instance.slug = unique_slug
                instance.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_generate_category_slugs'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, unique=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, unique=True, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, unique=True, null=True),
        ),
        migrations.RunPython(generate_slugs),
    ]