# Generated by Django 5.1 on 2024-09-17 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_generate_category_slugs'),
        ('core', '0012_category_slug_post_slug_post_tags_tag_slug'),
    ]

    operations = [
    ]
